spring:
  datasource:
    # ?serverTimezone=UTC 解决时区的报错
    url: jdbc:mysql://sh-cdb-b11akhd4.sql.tencentcdb.com:60170/demo_siahk?serverTimezone&useUnicode=true&characterEncoding=utf-8
    username: root
    password: mxqs6689**
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # Springboot 默认不注入这些属性值，需要自己绑定
    # druid 数据源专有配置
    dbcp2:
      initial-size: 5
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-create: false
      pool-prepared-statements: true
    tomcat:
      max-active: 20
      max-wait: 60000

    # 配置监控统计拦截的 filters，stat：监控统计，log4j：日志记录，wall：防御 sql 注入
    # 如果允许报错 java.lang.ClassNotFoundException:org.apache.log4j.Priority
    # 则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat, wall, log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    userGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true; druid.stat.slowSqlMillis=500
mybatis:
  type-aliases-package: com.heng.pojo
  mapper-locations: classpath:mapper/*.xml