server:
  servlet:
    context-path: /heng
spring:
  # 关闭模板引擎的缓存
  thymeleaf:
    cache: false
  # 我们配置文件的真实位置
  messages:
    basename: i18n.login
  mvc:
    # 时间日期格式化
    format:
      date-time: yyyy-MM-dd
  # 连接数据库
  datasource:
    username: root
    password: mxqs6689**
    url: jdbc:mysql://sh-cdb-b11akhd4.sql.tencentcdb.com:60170/demo_siahk?serverTimezone&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
# 整合mybatis
mybatis:
  type-aliases-package: com.heng.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml